In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("russian_museum_exhibitions_2014_2026_updated.csv")

In [9]:
df

,museum,place,title,date_range,year,period,url,description
0,Русский музей,Михайловский (Инженерный) замок,Степан Эрьзя – скульптор мира. К 150-летию со ...,1 апреля 2026 – 29 июня 2026,2026,post_2022,https://rusmuseum.ru/exhibitions/archive/stepa...,"В Год единства народов России, в Михайловском ..."
1,Русский музей,Михайловский (Инженерный) замок,Эпоха Императора Александра III и её наследие,26 декабря 2025 – 15 июня 2026,2025,post_2022,https://rusmuseum.ru/exhibitions/archive/epokh...,В год 180-летия со дня рождения Императора Але...
2,Русский музей,Корпус Бенуа,Архип Куинджи. Иллюзия света,11 сентября 2025 – 31 марта 2026,2025,post_2022,https://rusmuseum.ru/exhibitions/archive/arkhi...,«Архип Куинджи. Иллюзия света» — масштабная вы...
3,Русский музей,Корпус Бенуа,Русская традиция,13 декабря 2025 – 9 марта 2026,2025,post_2022,https://rusmuseum.ru/exhibitions/archive/russk...,Масштабная выставка «Русская традиция» в корпу...
4,Русский музей,Корпус Бенуа,Наш авангард,21 июня 2025 – 1 декабря 2025,2025,post_2022,https://rusmuseum.ru/exhibitions/archive/nash-...,"В Русском музее хранится уникальная по объему,..."
...,...,...,...,...,...,...,...,...
646,Русский музей,Михайловский дворец,Карл Брюллов из частных коллекций Москвы и Пет...,28 августа 2013 – 31 марта 2014,2014,pre_2022,https://rusmuseum.ru/exhibitions/archive/karl-...,Представленные на выставке десять абсолютно до...
647,Русский музей,Восточный павильон Михайловского замка,Романтический наш император,9 ноября 2017 – 13 февраля 2019,2019,pre_2022,https://rusmuseum.ru/exhibitions/archive/our-r...,Высокотехнологичная интерактивная экспозиция «...
648,Русский музей,Михайловский дворец,Памяти Ирины Яковлевны Богуславской. К 95-лети...,21 ноября 2024 – 10 марта 2025,2024,post_2022,https://rusmuseum.ru/exhibitions/archive/pamya...,Выставка посвящена Ирине Яковлевне Богуславско...
649,Русский музей,Мраморный дворец,Александр Павлов,23 ноября 2016 – 20 февраля 2017,2017,pre_2022,https://rusmuseum.ru/exhibitions/archive/alexa...,"Пейзаж, как универсальный образ природы, прямо..."
650,Русский музей,Мраморный дворец,Айдан Салахова. Из цикла «Новые святые»,24 июня 2021 – 25 октября 2021,2021,pre_2022,https://rusmuseum.ru/exhibitions/archive/aydan...,Замысел цикла «Новые святые» родился в московс...

In [10]:
df1 = df.sort_values(by='year')
df1

,museum,place,title,date_range,year,period,url,description
620,Русский музей,Михайловский (Инженерный) замок,Искусство как профессия. Собрание Майи и Анато...,9 июля 2014 – 1 сентября 2014,2014,pre_2022,https://rusmuseum.ru/exhibitions/archive/art-a...,На выставке в Русском музее представлено около...
604,Русский музей,Михайловский (Инженерный) замок,Дмитрий Шувалов. 1932-2013,5 ноября 2014 – 1 декабря 2014,2014,pre_2022,https://rusmuseum.ru/exhibitions/archive/dmitr...,Выставка знакомит с творчеством Заслуженного х...
625,Русский музей,Михайловский дворец,Цветы и натюрморты Александра Бенуа Ди Стетто,6 июня 2014 – 22 июня 2014,2014,pre_2022,https://rusmuseum.ru/exhibitions/archive/flowe...,"Имя Александра Бенуа ди Стетто (1896–1979), пр..."
624,Русский музей,Летний сад,Россия из окна поезда,9 июня 2014 – 28 июня 2014,2014,pre_2022,https://rusmuseum.ru/exhibitions/archive/russi...,"«Россия из окна поезда» — это проект, известно..."
623,Русский музей,Мраморный дворец,Бумажная скульптура,18 июня 2014 – 1 сентября 2014,2014,pre_2022,https://rusmuseum.ru/exhibitions/archive/paper...,Новая выставка Русского музея представляет бол...
...,...,...,...,...,...,...,...,...
23,Русский музей,Русский музей,Шагал. Прогулка в Художественном,8 апреля 2026 – 6 июля 2026,2026,post_2022,NaN,В Национальном художественном музее Республики...
22,Русский музей,Западный павильон Михайловского замка,Особенный мир,10 апреля 2026 – 17 мая 2026,2026,post_2022,https://rusmuseum.ru/exhibitions/archive/osobe...,В Центре мультимедиа Русского музея открылась ...
21,Русский музей,Восточный павильон Михайловского замка,Как на бумаге сказка оживает,29 апреля 2026 – 20 мая 2026,2026,post_2022,https://rusmuseum.ru/exhibitions/archive/kak-n...,29 апреля 2026 года в Восточном павильоне Миха...
19,Русский музей,Русский музей,Михаил Нестеров,15 мая 2026 – 28 июня 2026,2026,post_2022,NaN,В государственном музее-заповеднике «Ростовски...
0,Русский музей,Михайловский (Инженерный) замок,Степан Эрьзя – скульптор мира. К 150-летию со ...,1 апреля 2026 – 29 июня 2026,2026,post_2022,https://rusmuseum.ru/exhibitions/archive/stepa...,"В Год единства народов России, в Михайловском ..."

In [11]:
df1.to_csv("russian_museum_exhibitions_2014_2026_updated_ordered.csv", index=False)